crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models

from login import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
	url(r'^xadmin/', include(xadmin.site.urls)),

	#登录注册相关url
	url(r'^login/$',views.login,name='login'),
	url(r'^register/$',views.register,name='register'),
	url(r'^is_login/$',views.is_login,name='is_login'),
	url(r'^add_register/$',views.add_register,name='add_register'),
	url(r'^logout/$',views.logout,name='logout'),

	#后台页面相关url
	url(r'^admin_index/$', views.admin_index, name='admin_index'),
	url(r'^show_customers/$', views.show_customers, name='show_customers'),
	url(r'^add_customers/$', views.add_customers, name='add_customers'),
	url(r'^edit_customers/(\d+)/$', views.edit_customers, name='edit_customers'),


]

login/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class UserInfo(models.Model):
    """
    用户表：销售\讲师、班主任
    """
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=32)
    email = models.EmailField()
    telephone = models.CharField(max_length=16)
    is_active = models.BooleanField(default=True)
    depart = models.ForeignKey('Department',on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return self.username

    class Meta:
        ordering = ['id',]
        verbose_name='用户表'
        verbose_name_plural = '用户表'

class Department(models.Model):
    """
        部门表
    """
    name = models.CharField(max_length=32)
    count = models.IntegerField()

    class Meta:
        ordering = ['id',]
        verbose_name='部门表'
        verbose_name_plural = '部门表'

    def __str__(self):
        return self.name

class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True) #requierd:False
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名') #可为空，有些人就不愿意给自己的真实姓名
    sex_type = (('male', '男'), ('female', '女')) #
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True) #手机号改成字符串的，不然不好搜索
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)  #self指的就是自己这个表，和下面写法是一样的效果
    # '''
    # id  name introduce_from
    # 1   dz   None
    # 2   xf   1
    # 3   cg   1
    #
    # '''


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = models.CharField("咨询课程", max_length=128, choices=course_choices) #多选，并且存成一个列表的格式,通过modelform来用的时候，会成为一个多选框

    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True) #这个没啥用昂，我问销售，销售说是为了一周年的时候给客户发一个祝福信息啥的
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )


    # 一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",blank=True)


    # 成单日期，统计成单日期的时候会用到
    deal_date = models.DateField(null=True)


    class Meta:
        ordering = ['id',]
        verbose_name='客户信息表'
        verbose_name_plural = '客户信息表'

    def __str__(self):
        return self.name+":"+self.qq

    enroll_status_choices = (('signed', "已报名"),
                             ('unregistered', "未报名"),
                             ('studying', '学习中'),
                             ('paid_in_full', "学费已交齐"))
    def status_show(self):
        status_color = {
            'paid_in_full':'green',
            'unregistered':'red',
            'studying':'lightblue',
            'signed':'yellow',
        }

        return mark_safe("<span style='background-color:{0}'>{1}</span>".format(status_color[self.status],self.get_status_display()))
    def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id',]
        verbose_name='校区表'
        verbose_name_plural = '校区表'



class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True) #不一定什么时候结业，哈哈，所以可为空

    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师") #对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')
        ordering = ['id', ]
        verbose_name = '班级表'
        verbose_name_plural = '班级表'

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)
#
#
# ############################下面的表以后再说#################################
#
# # class ContractTemplate(models.Model):
# #     """
# #     合同模板表
# #     """
# #     name = models.CharField("合同名称", max_length=128, unique=True)
# #     content = models.TextField("合同内容")
# #     date = models.DateField(auto_now=True)
# #
# #
#
# class ConsultRecord(models.Model):
#     """
#     跟进记录表
#     """
#     customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
#     note = models.TextField(verbose_name="跟进内容...")
#     status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
#     consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
#     date = models.DateTimeField("跟进日期", auto_now_add=True)
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#     # def __str__(self):
#
#
#
# class Enrollment(models.Model):
#     """
#     报名表
#     """
#     why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
#     your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
#     # contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
#     contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
#     enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
#     memo = models.TextField('备注', blank=True, null=True)
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#     customer = models.ForeignKey('Customer', verbose_name='客户名称')
#     school = models.ForeignKey('Campuses')
#     enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")
#
#     class Meta:
#         unique_together = ('enrolment_class', 'customer')
#
#     def __str__(self):
#         return self.customer.name
# # class PaymentRecord(models.Model):
# #     """
# #     缴费记录表
# #     """
# #     pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
# #     paid_fee = models.IntegerField("费用数额", default=0)
# #     note = models.TextField("备注", blank=True, null=True)
# #     date = models.DateTimeField("交款日期", auto_now_add=True)

login/forms.py
#__*__coding:utf-8__*__
from django import forms
from django.forms import widgets
import re

from login import models


class UserForms(forms.Form):
	"""
	登陆表
	"""
	name = forms.CharField(
		label="用户名",
		max_length=16,
		required=True,
		widget=widgets.TextInput(attrs={'placeholder':"用户名"}),
	)
	pwd = forms.CharField(
		label="密码",
		max_length=128,
		required=True,
		widget=widgets.PasswordInput(attrs={'placeholder': "密码",}),
	)

class RegisterForm(forms.Form):
	"""
	注册表
	"""
	username = forms.CharField(
		min_length=3,
		max_length=8,
		required=True,
		widget=widgets.TextInput(attrs={'placeholder':'输入用户名'}),
		error_messages={
			'min_length': "用户名最少3个字符",
			'max_length': "用户名最多8个字符",
		}
	)

	password = forms.CharField(
		min_length=3,
		max_length=8,
		required=True,
		widget=widgets.PasswordInput(attrs={'placeholder':'输入密码','oncontextmenu':"return false"}),
	)
	re_password = forms.CharField(
		min_length=3,
		max_length=8,
		required=True,
		widget=widgets.PasswordInput(attrs={'placeholder':'再次输入密码','oncontextmenu':"return false"}),
	)
	telephone= forms.CharField(
		max_length=11,
		required=True,
		widget=widgets.TextInput(attrs={'placeholder':'输入手机号码',}),
	)
	email = forms.CharField(
		required=True,
		widget=widgets.EmailInput(attrs={'placeholder':'输入邮箱地址'}),
		error_messages={'invalid':"邮箱的格式不正确"}
	)

	def clean(self):
		"""
		全局钩子，验证数据
		:return:
		"""
		pwd = self.cleaned_data.get('password')
		re_pwd = self.cleaned_data.get('re_password')
		if pwd == re_pwd:
			return self.cleaned_data
		else:
			self.add_error('re_password',"两次密码不一致")

	def clean_phone(self):
		"""
		局部钩子,验证手机号是否正确
		:return:
		"""
		telephone = self.cleaned_data.get("telephone")
		mobile_re = re.compile(r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$')
		if not mobile_re.match(telephone):
			self.add_error('telephone','手机号码格式错误')
		else:
			#注意，使用钩子检查数据的时候，数据没有问题，一定把对象返回，否者在view里面是拿不到数据的
			return telephone

class CustomersModelsForm(forms.ModelForm):
	"""
	添加客户
	"""
	class Meta:
		model = models.Customer
		fields = "__all__"

		def __init__(self,*args,**kwargs):
			super().__str__(*args,**kwargs)

			for field_name,field in self.fields.items():
				from multiselectfield.forms.fields import MultiSelectFormField
				if not isinstance(field,MultiSelectFormField):
					field.widget.attrs.update({'class':'form-control'})

login/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse

from login import forms
from login import models
from utils import hash_pwd
# Create your views here.

def login(request):
	"""
	登陆
	:param request:
	:return:
	"""
	form = forms.UserForms()
	return render(request, 'login/login.html', {'form':form})

def is_login(request):
	"""
	处理登陆提交的数据，判断登陆是否成功
	:param request:
	:return:
	"""
	form = forms.UserForms(request.POST)
	if form.is_valid():
		data = form.cleaned_data
		has_password= hash_pwd.has_password(data['pwd'])
		ret = models.UserInfo.objects.filter(password=has_password).first()
		if ret:
			request.session['is_login'] = "user"
			status = {"data": 1}
			return JsonResponse(status)
		else:
			status = {"data": 0}
			return JsonResponse(status)
	else:
		return render(request, "login/login.html", {"form": form})

def register(request):
	"""
	注册
	:param request:
	:return:
	"""
	form = forms.RegisterForm()    #注意，request.POST是前台传过来的，我们能如果在这里加的话，前端页面会展示出为空的错误
	return render(request, 'login/register.html', {"form":form})

def add_register(request):
	"""
	处理注册提交的数据，保存到数据库
	:param request:
	:return:
	"""
	form = forms.RegisterForm(request.POST)
	if form.is_valid():
		data = form.cleaned_data
		print (data)
		#清洗数据
		data.pop("re_password")
		data['password'] = hash_pwd.has_password(data.get('password'))
		#添加必要数据
		data['is_active'] = 1
		#格式化储存
		models.UserInfo.objects.create(
			**data
		)
		return redirect('login')
	else:
		#把前端提交的包含错误信息的对象返回到前端页面
		return render(request, 'login/register.html', {"form":form})

def admin_index(request):
	"""
	后台主界面
	:param request:
	:return:
	"""
	return render(request, "index.html", )

def show_customers(request):
	"""
	展示客户信息页面
	:param request:
	:return:
	"""
	customers_info = models.Customer.objects.all()
	return render(request,'customers/show_customers.html',{"customers_info":customers_info})

def add_customers(request):
	"""
	增加客户信息页面
	:param request:
	:return:
	"""
	if request.method == "GET":
		form = forms.CustomersModelsForm()
		return render(request,'customers/add_customers.html',{"form":form})
	else:
		form = forms.CustomersModelsForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('show_customers')
		else:
			return render(request,'customers/add_customers.html',{"form":form})

def edit_customers(request,id):
	"""
	修改客户信息页面
	:param request:
	:return:
	"""
	old_obj = models.Customer.objects.filter(pk=id).first()
	if request.method == "GET":
		old_form = forms.CustomersModelsForm(instance=old_obj)
		return render(request,'customers/edit_cumtomers.html',{"form":old_form})
	else:
		new_form = forms.CustomersModelsForm(request.POST,instance=old_obj)
		if new_form.is_valid():
			new_form.save()
			return redirect('show_customers')
		else:
			return render(request,'customers/edit_cumtomers.html',{"form":new_form})

'''
结合add和edit：
def addEditCustomer(request,n=None):
    old_obj = models.Customer.objects.filter(pk=n).first()
    label  = '编辑页面' if n else '添加页面'


    if request.method == 'GET':
        book_form_obj = myforms.CustomerModelForm(instance=old_obj)
        return render(request, 'customer/editcustomer.html', {'book_form_obj': book_form_obj,'label':label})

    else:
        book_form_obj = myforms.CustomerModelForm(request.POST,instance=old_obj)

        if book_form_obj.is_valid():
            book_form_obj.save()
            return redirect('customers')
        else:

            return render(request, 'customer/editcustomer.html', {'book_form_obj': book_form_obj,'label':label})
'''

def logout(request):
	"""
	退出登陆
	:param request:
	:return:
	"""
	if request.session.get("is_login"):
		request.session.flush()
	return redirect("login")

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0050)http://www.jq22.com/demo/jquery-Sharelink20151012/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>登陆</title>

    {#静态文件的3种引用方式#}
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
{#    <link rel="stylesheet" href="/statics/css/style.css">#}
{#    <link rel="stylesheet" href="/statics/css/style.css">#}

</head>
<body>
<div class="login-container">
    <h1>欢迎来到爸爸的怀抱</h1>
    <div class="connect">
        <p style="left: 0%;">Link the world. Share to world.</p>
    </div>
{#    <form action="{% url "is_login" %}" method="post" id="loginForm"#}
{#          novalidate="novalidate">#}
{#        {% csrf_token %}#}
{#        <div>#}
{#            <input type="text" name="username" class="username" placeholder="用户名" autocomplete="off" >#}
{#        </div>#}
{#        <div>#}
{#            <input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false"#}
{#                   onpaste="return false">#}
{#        </div>#}
        <div>
            {{ form.name }}<span>{{ form.errors.0 }}</span>
        </div>

        <div>
            {{ form.pwd }}<span>{{ form.errors.0 }}</span>
        </div>
        <div>
            <button id="submit" type="button">登 陆</button>
        </div>
{#    </form>#}
    <a href="{% url "register" %}">
        <div>
            <button type="button" class="register-tis">还有没有账号？</button>
        </div>
    </a>
</div>

<script src="{% static 'login/js/jquery.min.js' %}"></script>
<script src="{% static 'login/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'login/js/common.js' %}"></script>
<script src="{% static 'login/js/supersized-init.js' %}"></script>
<script src="{% static 'login/js/supersized.3.2.7.min.js' %}"></script>

<ul id="supersized" class="quality" style="visibility: visible;">
    <li class="slide-0 activeslide" style="visibility: visible; opacity: 1;"><a target="_blank"><img
            src="{% static 'login/img/1.jpg' %}" style="width: 1904px; left: 0px; top: -151px; height: 1199.52px;"></a></li>
    <li class="slide-1" style="visibility: visible; opacity: 1;"><a target="_blank"><img
            src="../../statics/login/img/2.jpg" style="width: 1904px; left: 0px; top: -217.5px; height: 1332.8px;"></a>
    </li>
    <li class="slide-2 prevslide" style="visibility: visible; opacity: 1;"><a target="_blank"><img
            src="{% static 'login/img/3.jpg' %}" style="width: 1904px; height: 1199.52px; left: 0px; top: -151px;"></a></li>
</ul>

<script>
    $('#submit').click(function () {
        var name = $('#id_name').val();
        var pwd = $('#id_pwd').val();
        $.ajax({
            url:'{% url 'is_login'%}',
            type:'post',
            data:{'name':name,'pwd':pwd,'csrfmiddlewaretoken':'{{csrf_token}}'},
            success:function (res) {
                if (res.data === 1){
                    location.href = "{% url 'admin_index' %}"
                }else{
                    alert("用户名或者密码错误！")
                }
            }
        })

    })
</script>

</body>
</html>

templates/login/register.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0063)http://www.jq22.com/demo/jquery-Sharelink20151012/register.html -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>注册丨Sharelink</title>
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
</head>
<body>
<div class="register-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p style="left: 0%;">Link the world. Share to world.</p>
    </div>
    <form action="{% url "add_register" %}" method="post" id="registerForm"
          novalidate="novalidate">
    {% csrf_token %}
{#        <div>#}
{#            <input type="text" name="username" class="username" placeholder="您的用户名" autocomplete="off">#}
{#        </div>#}
{#        <div>#}
{#            <input type="password" name="password" class="password" placeholder="输入密码" oncontextmenu="return false"#}
{#                   onpaste="return false">#}
{#        </div>#}
{#        <div>#}
{#            <input type="password" name="confirm_password" class="confirm_password" placeholder="再次输入密码"#}
{#                   oncontextmenu="return false" onpaste="return false">#}
{#        </div>#}
{#        <div>#}
{#            <input type="text" name="phone_number" class="phone_number" placeholder="输入手机号码" autocomplete="off"#}
{#                   id="number">#}
{#        </div>#}
{#        <div>#}
{#            <input type="email" name="email" class="email" placeholder="输入邮箱地址" oncontextmenu="return false"#}
{#                   onpaste="return false">#}
{#        </div>#}
        {% for field in form %}
            <div>
                {{ field }}
                {{ field.errors.0 }}
            </div>
        {% endfor %}
        <button id="submit" type="submit">注 册</button>
    </form>
    <a href="{% url "login" %}">
        <button type="button" class="register-tis">已经有账号？</button>
    </a>
</div>

<script src="{% static 'login/js/jquery.min.js' %}"></script>
<script src="{% static 'login/js/common.js' %}"></script>
<script src="{% static 'login/js/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'login/js/supersized-init.js' %}"></script>
<script src="{% static 'login/js/jquery.validate.min.js' %}"></script>

<ul id="supersized" class="speed" style="visibility: visible;">
    <li class="slide-0 activeslide" style="visibility: visible; opacity: 0.53453;"><a target="_blank"><img
            src="{% static 'login/img/1.jpg' %}" style="width: 1887px; left: 0px; top: -302px; height: 1188.81px;"></a></li>
    <li class="slide-1" style="visibility: visible; opacity: 1;"><a target="_blank"><img
            src="{% static 'login/img/2.jpg' %}" style="width: 1887px; left: 0px; top: -368px; height: 1320.9px;"></a></li>
    <li class="slide-2 prevslide" style="visibility: visible; opacity: 1;"><a target="_blank"><img
            src="{% static 'login/img/3.jpg' %}" style="width: 1887px; height: 1188.81px; left: 0px; top: -302px;"></a></li>
</ul>
</body>
</html>